In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
%matplotlib inline

In [2]:
data = pd.read_csv("insurance_data.csv")
data.head()

   age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [3]:
data.shape

(28, 3)

In [4]:
data.columns

Index(['age', 'affordibility', 'bought_insurance'], dtype='str')

In [5]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    data[["age", "affordibility"]],
    data.bought_insurance,
    test_size=0.2,
    random_state=25,
)

In [6]:
x_train

    age  affordibility
0    22              1
13   29              0
6    55              0
17   58              1
24   50              1
19   18              1
25   54              1
16   25              0
20   21              1
3    52              0
7    60              0
1    25              0
5    56              1
27   46              1
8    62              1
18   19              0
12   27              0
23   45              1
22   40              1
15   55              1
26   23              1
4    46              1

In [7]:
x_test

    age  affordibility
2    47              1
10   18              1
21   26              0
11   28              1
14   49              1
9    61              1

In [8]:
x_train_scaled = x_train.copy()
x_train_scaled["age"] = x_train_scaled["age"] / 100

x_test_scaled = x_test.copy()
x_test_scaled["age"] = x_test_scaled["age"] / 100

In [9]:
x_train_scaled

     age  affordibility
0   0.22              1
13  0.29              0
6   0.55              0
17  0.58              1
24  0.50              1
19  0.18              1
25  0.54              1
16  0.25              0
20  0.21              1
3   0.52              0
7   0.60              0
1   0.25              0
5   0.56              1
27  0.46              1
8   0.62              1
18  0.19              0
12  0.27              0
23  0.45              1
22  0.40              1
15  0.55              1
26  0.23              1
4   0.46              1

In [10]:
from tensorflow import keras

In [11]:
model = keras.Sequential(
    [
        keras.layers.Dense(
            1,
            input_shape=(2,),
            activation="sigmoid",
            bias_initializer="zeros",
            kernel_initializer="ones",
        )
    ]
)

d:\Python\TensorFlow\.venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [12]:
model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [13]:
# model.fit(x_train_scaled, y_train, epochs=5000)

In [14]:
# model.evaluate(x_test_scaled, y_test)

In [15]:
x_test_scaled

     age  affordibility
2   0.47              1
10  0.18              1
21  0.26              0
11  0.28              1
14  0.49              1
9   0.61              1

In [16]:
# model.predict(x_test_scaled)

In [17]:
y_test

2     1
10    0
21    0
11    0
14    1
9     1
Name: bought_insurance, dtype: int64

In [18]:
# coef, intercept = model.get_weights()

In [19]:
# coef, intercept

In [20]:
import math


def sigmoid(x):
    return 1 / (1 + math.exp(-x))


sigmoid(18)

0.9999999847700205

In [ ]:
# def prediction_function(age, affordibility):
#     weighted_some = coef[0][0] * age + coef[1][0] * affordibility + intercept[0]
#     return sigmoid(weighted_some)

In [23]:
# prediction_function(0.47, 1)

In [24]:
def log_loss(y_true, y_pred):
    epsilon = 1e-15
    y_pred_new = [max(i, epsilon) for i in y_pred]
    y_pred_new = [min(i, 1 - epsilon) for i in y_pred_new]
    y_pred_new = np.array(y_pred_new)
    return -np.mean(y_true * np.log(y_pred_new) + (1 - y_true) * np.log(1 - y_pred_new))

In [25]:
def sigmoid_numpy(x):
    return 1 / (1 + np.exp(-x))


sigmoid_numpy(np.array([12, 0, 1]))

array([0.99999386, 0.5       , 0.73105858])

In [33]:
class myNN:
    def __init__(self):
        self.w1 = 1
        self.w2 = 1
        self.bias = 0

    def fit(self, x, y, epochs, loss_treshold):
        self.w1, self.w2, self.bias = self.gradient_descent(
            x["age"], x["affordibility"], y, epochs, loss_treshold
        )

    def predict(self, x_test):
        weighted_sum = self.w1*x_test["age"] + self.w2*x_test["affordibility"] + self.bias
        y_pred = sigmoid_numpy(weighted_sum)
        return y_pred

    def gradient_descent(self, age, affordibility, y_true, epochs, loss_treshold):
        w1 = w2 = 1
        bias = 0
        rate = 0.5
        n = len(age)

        for i in range(epochs):
            weighted_sum = w1 * age + w2 * affordibility + bias
            y_pred = sigmoid_numpy(weighted_sum)
            loss = log_loss(y_true, y_pred)

            w1d = (1 / n) * np.dot(np.transpose(age), (y_pred - y_true))
            w2d = (1 / n) * np.dot(np.transpose(affordibility), (y_pred - y_true))
            bias_d = np.mean(y_pred - y_true)
            w1 = w1 - rate * w1d
            w2 = w2 - rate * w2d
            bias = bias - rate * bias_d
            if i % 50 == 0:
                print(f"epoch: {i}, loss: {loss}, w1: {w1}, w2: {w2}, bias: {bias}")
            if loss <= loss_treshold:
                break

        return w1, w2, bias

In [26]:
def gradient_descent(age, affordibility, y_true, epochs, loss_treshold):
    w1 = w2 = 1
    bias = 0
    rate = 0.5
    n = len(age)

    for i in range(epochs):
        weighted_sum = w1 * age + w2 * affordibility + bias
        y_pred = sigmoid_numpy(weighted_sum)
        loss = log_loss(y_true, y_pred)

        w1d = (1 / n) * np.dot(np.transpose(age), (y_pred - y_true))
        w2d = (1 / n) * np.dot(np.transpose(affordibility), (y_pred - y_true))
        bias_d = np.mean(y_pred - y_true)
        w1 = w1 - rate * w1d
        w2 = w2 - rate * w2d
        bias = bias - rate * bias_d
        print(f"epoch: {i}, loss: {loss}, w1: {w1}, w2: {w2}, bias: {bias}")
        if loss <= loss_treshold:
            break
    return w1, w2, bias

In [27]:
gradient_descent(
    x_train_scaled["age"], x_train_scaled["affordibility"], y_train, 1000, 0.4631
)

epoch: 0, loss: 0.7113403233723417, w1: 0.974907633470177, w2: 0.948348125394529, bias: -0.11341867736368583
epoch: 1, loss: 0.681264778737757, w1: 0.9556229728273669, w2: 0.9058873696677865, bias: -0.2122349122718517
epoch: 2, loss: 0.6591474252715025, w1: 0.9416488476693794, w2: 0.8719790823960313, bias: -0.2977578997796538
epoch: 3, loss: 0.6431523291301917, w1: 0.9323916996249162, w2: 0.8457541517722915, bias: -0.3715094724003511
epoch: 4, loss: 0.6316873063379158, w1: 0.9272267472726993, w2: 0.8262362885332687, bias: -0.43506643026891584
epoch: 5, loss: 0.623471707997592, w1: 0.9255469396815343, w2: 0.8124402814952774, bias: -0.48994490058938817
epoch: 6, loss: 0.6175321183044205, w1: 0.9267936114129968, w2: 0.8034375029757677, bias: -0.5375299543522853
epoch: 7, loss: 0.6131591858705934, w1: 0.93047170420295, w2: 0.7983920007454487, bias: -0.5790424270894963
epoch: 8, loss: 0.6098518179750948, w1: 0.9361540784567942, w2: 0.7965748796787705, bias: -0.6155315088627655
epoch: 9, loss: 0.6072639970231438, w1: 0.9434791243557357, w2: 0.7973647616854131, bias: -0.6478828179413606
epoch: 10, loss: 0.6051606942838051, w1: 0.9521448361628082, w2: 0.8002404280558159, bias: -0.6768343869109611
epoch: 11, loss: 0.6033841405177724, w1: 0.9619014360798376, w2: 0.8047697991276092, bias: -0.7029956527236098
epoch: 12, loss: 0.6018292976282692, w1: 0.9725437902239876, w2: 0.8105978078160995, bias: -0.7268665798879941
epoch: 13, loss: 0.6004266142491015, w1: 0.9839042828641819, w2: 0.8174345999952901, bias: -0.7488554155033402
epoch: 14, loss: 0.5991301804031037, w1: 0.9958464546516588, w2: 0.8250447751055391, bias: -0.769294418817745
epoch: 15, loss: 0.5979097221992564, w1: 1.0082595007242081, w2: 0.8332379503132499, bias: -0.7884533918133878
epoch: 16, loss: 0.5967452540340851, w1: 1.0210536111133566, w2: 0.8418606908070436, bias: -0.8065510935633605
epoch: 17, loss: 0.5956235357679642, w1: 1.034156080666481, w2: 0.8507897246509063, bias: -0.8237647415878959
epoch: 18, loss: 0.5945357398126384, w1: 1.0475080939682688, w2: 0.8599263049589658, bias: -0.8402378469114854
epoch: 19, loss: 0.5934759216594547, w1: 1.0610620872868053, w2: 0.8691915649552581, bias: -0.8560866317233403
epoch: 20, loss: 0.5924400203169505, w1: 1.0747795953648005, w2: 0.8785227146485403, bias: -0.8714052604012273
epoch: 21, loss: 0.5914252065214394, w1: 1.0886295007650375, w2: 0.8878699408379153, bias: -0.8862700880092956
epoch: 22, loss: 0.5904294583596238, w1: 1.1025866146156011, w2: 0.8971938890119441, bias: -0.9007431016492755
epoch: 23, loss: 0.5894512852039241, w1: 1.1166305284975315, w2: 0.9064636231844676, bias: -0.9148747025148294
epoch: 24, loss: 0.5884895481881011, w1: 1.130744687166233, w2: 0.9156549761872753, bias: -0.9287059516737735
epoch: 25, loss: 0.5875433434377384, w1: 1.1449156405234902, w2: 0.9247492176815199, bias: -0.9422703810055986
epoch: 26, loss: 0.5866119260562087, w1: 1.1591324407175467, w2: 0.9337319799254573, bias: -0.9555954523596437
epoch: 27, loss: 0.5856946605640079, w1: 1.1733861565198167, w2: 0.9425923921787205, bias: -0.9687037326284236
epoch: 28, loss: 0.5847909885040025, w1: 1.1876694823356402, w2: 0.9513223836938425, bias: -0.9816138397030203
epoch: 29, loss: 0.5839004071862915, w1: 1.2019764234961199, w2: 0.9599161227563919, bias: -0.994341203820797
epoch: 30, loss: 0.5830224556644095, w1: 1.2163020429886013, w2: 0.9683695654077998, bias: -1.006898680274023
epoch: 31, loss: 0.5821567054089575, w1: 1.2306422576428844, w2: 0.9766800925300213, bias: -1.0192970425003876
epoch: 32, loss: 0.5813027540359855, w1: 1.244993674111329, w2: 0.9848462180774323, bias: -1.0315453789434794
epoch: 33, loss: 0.5804602210251408, w1: 1.2593534568600255, w2: 0.9928673545729692, bias: -1.0436514125153917
epoch: 34, loss: 0.5796287447370064, w1: 1.2737192219062514, w2: 1.0007436246821175, bias: -1.0556217578155669
epoch: 35, loss: 0.57880798028165, w1: 1.2880889512619975, w2: 1.0084757098569885, bias: -1.067462128294764
epoch: 36, loss: 0.5779975979476322, w1: 1.3024609240300042, w2: 1.0160647288004139, bias: -1.079177503164993
epoch: 37, loss: 0.5771972820026156, w1: 1.3168336608930384, w2: 1.0235121399165894, bias: -1.0907722619345364
epoch: 38, loss: 0.5764067297427645, w1: 1.331205879376151, w2: 1.0308196630555955, bias: -1.1022502929016078
epoch: 39, loss: 0.5756256507109632, w1: 1.345576457775507, w2: 1.03798921677727, bias: -1.1136150806976406
epoch: 40, loss: 0.5748537660316542, w1: 1.3599444060604626, w2: 1.0450228680985851, bias: -1.124869776972519
epoch: 41, loss: 0.5740908078281305, w1: 1.3743088423875547, w2: 1.0519227922827652, bias: -1.1360172575115421
epoch: 42, loss: 0.5733365186998217, w1: 1.3886689741318718, w2: 1.0586912407061275, bias: -1.1470601684290498
epoch: 43, loss: 0.5725906512447178, w1: 1.403024082555677, w2: 1.065330515222758, bias: -1.1580009635655026
epoch: 44, loss: 0.5718529676170188, w1: 1.4173735104064384, w2: 1.0718429477560005, bias: -1.1688419347984433
epoch: 45, loss: 0.5711232391133308, w1: 1.431716651874893, w2: 1.0782308840940895, bias: -1.1795852366431911
epoch: 46, loss: 0.5704012457828124, w1: 1.446052944455051, w2: 1.0844966710669584, bias: -1.1902329062502135
epoch: 47, loss: 0.5696867760580652, w1: 1.4603818623375084, w2: 1.0906426464418717, bias: -1.2007868796899672
epoch: 48, loss: 0.5689796264044564, w1: 1.474702911039356, w2: 1.0966711310047097, bias: -1.2112490052422353
epoch: 49, loss: 0.5682796009861607, w1: 1.4890156230318012, w2: 1.1025844223976542, bias: -1.2216210542672539
epoch: 50, loss: 0.5675865113475955, w1: 1.503319554173139, w2: 1.108384790367645, bias: -1.2319047301235464
epoch: 51, loss: 0.5669001761092021, w1: 1.5176142807921111, w2: 1.1140744731472638, bias: -1.2421016755069894
epoch: 52, loss: 0.566220420676692, w1: 1.5318993972968091, w2: 1.1196556747438646, bias: -1.2522134785128962
epoch: 53, loss: 0.5655470769630154, w1: 1.546174514208496, w2: 1.1251305629563741, bias: -1.2622416776643735
epoch: 54, loss: 0.5648799831223866, w1: 1.5604392565392238, w2: 1.1305012679742994, bias: -1.2721877661030871
epoch: 55, loss: 0.5642189832957764, w1: 1.5746932624478314, w2: 1.1357698814417572, bias: -1.2820531951006382
epoch: 56, loss: 0.5635639273673236, w1: 1.5889361821215457, w2: 1.1409384558921223, bias: -1.2918393770181935
epoch: 57, loss: 0.562914670731162, w1: 1.6031676768405996, w2: 1.1460090044772484, bias: -1.3015476878174077
epoch: 58, loss: 0.5622710740681858, w1: 1.6173874181914885, w2: 1.150983500930006, bias: -1.3111794692058374
epoch: 59, loss: 0.5616330031323111, w1: 1.6315950874010996, w2: 1.155863879710811, bias: -1.320736030484068
epoch: 60, loss: 0.5610003285458062, w1: 1.6457903747692835, w2: 1.1606520362984267, bias: -1.3302186501488862
epoch: 61, loss: 0.5603729256032908, w1: 1.6599729791817353, w2: 1.1653498275930778, bias: -1.3396285772964385
epoch: 62, loss: 0.5597506740840237, w1: 1.6741426076885264, w2: 1.1699590724061661, bias: -1.348967032860937
epoch: 63, loss: 0.5591334580721091, w1: 1.6882989751364197, w2: 1.1744815520159209, bias: -1.3582352107177078
epoch: 64, loss: 0.5585211657842806, w1: 1.7024418038453646, w2: 1.1789190107723873, bias: -1.3674342786739169
epoch: 65, loss: 0.5579136894049259, w1: 1.7165708233213919, w2: 1.1832731567384374, bias: -1.3765653793659074
epoch: 66, loss: 0.5573109249280388, w1: 1.7306857699995972, w2: 1.1875456623561378, bias: -1.385629631078514
epoch: 67, loss: 0.556712772005794, w1: 1.744786387012096, w2: 1.1917381651299463, bias: -1.3946281284988502
epoch: 68, loss: 0.5561191338034575, w1: 1.7588724239767908, w2: 1.1958522683199346, bias: -1.4035619434147377
epoch: 69, loss: 0.5555299168603557, w1: 1.7729436368035707, w2: 1.199889541639625, bias: -1.412432125366066
epoch: 70, loss: 0.55494503095664, w1: 1.786999787515191, w2: 1.2038515219541523, bias: -1.4212397022558536
epoch: 71, loss: 0.5543643889855958, w1: 1.8010406440805895, w2: 1.2077397139753707, bias: -1.4299856809265468
epoch: 72, loss: 0.5537879068312537, w1: 1.815065980258806, w2: 1.21155559095125, bias: -1.4386710477060998
epoch: 73, loss: 0.5532155032510755, w1: 1.8290755754520085, w2: 1.2153005953475013, bias: -1.4472967689275704
epoch: 74, loss: 0.5526470997634942, w1: 1.8430692145663952, w2: 1.2189761395198406, bias: -1.4558637914253105
epoch: 75, loss: 0.5520826205400979, w1: 1.857046687879965, w2: 1.2225836063756854, bias: -1.4643730430103006
epoch: 76, loss: 0.5515219923022593, w1: 1.8710077909163219, w2: 1.2261243500243837, bias: -1.472825432926746
epoch: 77, loss: 0.5509651442220168, w1: 1.8849523243238275, w2: 1.2295996964153224, bias: -1.4812218522917016
epoch: 78, loss: 0.5504120078270269, w1: 1.898880093759531, w2: 1.2330109439634602, bias: -1.4895631745192046
epoch: 79, loss: 0.5498625169094129, w1: 1.9127909097773987, w2: 1.2363593641619885, bias: -1.4978502557301687
epoch: 80, loss: 0.5493166074383391, w1: 1.9266845877204517, w2: 1.2396462021819508, bias: -1.5060839351490927
epoch: 81, loss: 0.5487742174761587, w1: 1.9405609476164691, w2: 1.2428726774587495, bias: -1.5142650354884937
epoch: 82, loss: 0.5482352870979753, w1: 1.9544198140769822, w2: 1.2460399842655545, bias: -1.5223943633218389
epoch: 83, loss: 0.5476997583144769, w1: 1.968261016199314, w2: 1.2491492922736824, bias: -1.5304727094456483
epoch: 84, loss: 0.5471675749979029, w1: 1.9820843874714607, w2: 1.252201747100074, bias: -1.538500849231359
epoch: 85, loss: 0.5466386828110088, w1: 1.995889765679638, w2: 1.2551984708420285, bias: -1.5464795429674643
epoch: 86, loss: 0.5461130291389041, w1: 2.0096769928183367, w2: 1.2581405625993878, bias: -1.554409536192387
epoch: 87, loss: 0.545590563023641, w1: 2.023445915002755, w2: 1.2610290989843815, bias: -1.5622915600184968
epoch: 88, loss: 0.5450712351014357, w1: 2.037196382383489, w2: 1.2638651346193672, bias: -1.5701263314476384
epoch: 89, loss: 0.5445549975424178, w1: 2.0509282490633733, w2: 1.2666497026227028, bias: -1.577914553678509
epoch: 90, loss: 0.5440418039927909, w1: 2.0646413730163813, w2: 1.2693838150830055, bias: -1.585656916406187
epoch: 91, loss: 0.5435316095193146, w1: 2.0783356160084976, w2: 1.2720684635220503, bias: -1.5933540961140944
epoch: 92, loss: 0.5430243705560023, w1: 2.092010843520487, w2: 1.2747046193465692, bias: -1.6010067563586592
epoch: 93, loss: 0.5425200448529465, w1: 2.1056669246724873, w2: 1.2772932342892063, bias: -1.6086155480469115
epoch: 94, loss: 0.5420185914271816, w1: 2.1193037321503643, w2: 1.2798352408388918, bias: -1.6161811097072503
epoch: 95, loss: 0.5415199705154982, w1: 2.1329211421337653, w2: 1.282331552660889, bias: -1.62370406775359
epoch: 96, loss: 0.5410241435291299, w1: 2.1465190342258187, w2: 1.2847830650067702, bias: -1.6311850367430925
epoch: 97, loss: 0.5405310730102341, w1: 2.1600972913844236, w2: 1.2871906551145709, bias: -1.638624619627673
epoch: 98, loss: 0.5400407225900913, w1: 2.173655799855084, w2: 1.2895551825993699, bias: -1.6460234079994696
epoch: 99, loss: 0.5395530569489538, w1: 2.1871944491052364, w2: 1.2918774898345378, bias: -1.6533819823304428
epoch: 100, loss: 0.5390680417774752, w1: 2.200713131760032, w2: 1.2941584023238903, bias: -1.6607009122062801
epoch: 101, loss: 0.5385856437396539, w1: 2.2142117435395288, w2: 1.2963987290649803, bias: -1.667980756554761
epoch: 102, loss: 0.5381058304372313, w1: 2.227690183197251, w2: 1.298599262903754, bias: -1.675222063868738
epoch: 103, loss: 0.5376285703754836, w1: 2.241148352460086, w2: 1.300760780880796, bias: -1.6824253724238831
epoch: 104, loss: 0.5371538329303491, w1: 2.2545861559694704, w2: 1.302884044569378, bias: -1.68959121049134
epoch: 105, loss: 0.5366815883168389, w1: 2.268003501223843, w2: 1.3049698004055226, bias: -1.696720096545423
epoch: 106, loss: 0.5362118075586769, w1: 2.281400298522321, w2: 1.30701878001029, bias: -1.7038125394664934
epoch: 107, loss: 0.5357444624591193, w1: 2.294776460909571, w2: 1.3090317005044871, bias: -1.7108690387391425
epoch: 108, loss: 0.5352795255729065, w1: 2.308131904121845, w2: 1.3110092648159952, bias: -1.717890084645807
epoch: 109, loss: 0.5348169701793002, w1: 2.3214665465341486, w2: 1.3129521619799067, bias: -1.7248761584559342
epoch: 110, loss: 0.5343567702561651, w1: 2.334780309108516, w2: 1.3148610674316565, bias: -1.7318277326108187
epoch: 111, loss: 0.5338989004550466, w1: 2.3480731153433556, w2: 1.3167366432933292, bias: -1.7387452709042173
epoch: 112, loss: 0.5334433360772121, w1: 2.361344891223853, w2: 1.318579538653317, bias: -1.7456292286588566
epoch: 113, loss: 0.5329900530506113, w1: 2.3745955651733888, w2: 1.3203903898394993, bias: -1.752480052898938
epoch: 114, loss: 0.532539027907722, w1: 2.387825068005961, w2: 1.3221698206861112, bias: -1.759298182518741
epoch: 115, loss: 0.5320902377642434, w1: 2.4010333328795768, w2: 1.3239184427944621, bias: -1.7660840484474298
epoch: 116, loss: 0.5316436602986057, w1: 2.4142202952505927, w2: 1.3256368557876617, bias: -1.772838073810153
epoch: 117, loss: 0.5311992737322607, w1: 2.427385892828985, w2: 1.3273256475595065, bias: -1.7795606740855376
epoch: 118, loss: 0.5307570568107249, w1: 2.440530065534521, w2: 1.328985394517677, bias: -1.7862522572596642
epoch: 119, loss: 0.5303169887853427, w1: 2.4536527554538115, w2: 1.3306166618213877, bias: -1.7929132239766132
epoch: 120, loss: 0.5298790493957434, w1: 2.46675390679823, w2: 1.332220003613633, bias: -1.7995439676856702
epoch: 121, loss: 0.5294432188529623, w1: 2.479833465862666, w2: 1.3337959632481655, bias: -1.8061448747852695
epoch: 122, loss: 0.5290094778232023, w1: 2.4928913809851023, w2: 1.3353450735113397, bias: -1.8127163247637639
epoch: 123, loss: 0.5285778074122077, w1: 2.505927602506996, w2: 1.336867856838949, bias: -1.8192586903370926
epoch: 124, loss: 0.5281481891502279, w1: 2.518942082734439, w2: 1.3383648255281848, bias: -1.82577233758343
epoch: 125, loss: 0.5277206049775486, w1: 2.5319347759000843, w2: 1.3398364819448387, bias: -1.832257626074885
epoch: 126, loss: 0.5272950372305655, w1: 2.5449056381258233, w2: 1.341283318725866, bias: -1.8387149090063277
epoch: 127, loss: 0.5268714686283816, w1: 2.557854627386187, w2: 1.3427058189774277, bias: -1.8451445333214114
epoch: 128, loss: 0.5264498822599072, w1: 2.570781703472466, w2: 1.3441044564685245, bias: -1.851546839835858
epoch: 129, loss: 0.5260302615714416, w1: 2.583686827957526, w2: 1.3454796958203281, bias: -1.857922163358077
epoch: 130, loss: 0.5256125903547197, w1: 2.596569964161304, w2: 1.3468319926913221, bias: -1.8642708328071762
epoch: 131, loss: 0.5251968527354036, w1: 2.6094310771169726, w2: 1.3481617939583523, bias: -1.8705931713284367
epoch: 132, loss: 0.524783033162003, w1: 2.6222701335377554, w2: 1.3494695378936878, bias: -1.8768894964063034
epoch: 133, loss: 0.5243711163952075, w1: 2.635087101784378, w2: 1.3507556543381916, bias: -1.8831601199749577
epoch: 134, loss: 0.5239610874976152, w1: 2.647881951833145, w2: 1.3520205648706967, bias: -1.8894053485265268
epoch: 135, loss: 0.5235529318238407, w1: 2.660654655244622, w2: 1.3532646829736783, bias: -1.8956254832169885
epoch: 136, loss: 0.5231466350109902, w1: 2.6734051851329177, w2: 1.354488414195315, bias: -1.901820819969824
epoch: 137, loss: 0.5227421829694883, w1: 2.686133516135547, w2: 1.3556921563080244, bias: -1.9079916495774736
epoch: 138, loss: 0.5223395618742417, w1: 2.6988396243838655, w2: 1.3568762994635604, bias: -1.9141382578006458
epoch: 139, loss: 0.5219387581561294, w1: 2.7115234874740595, w2: 1.3580412263447548, bias: -1.920260925465534
epoch: 140, loss: 0.5215397584938058, w1: 2.724185084438686, w2: 1.359187312313983, bias: -1.9263599285589843
epoch: 141, loss: 0.5211425498058037, w1: 2.736824395718745, w2: 1.360314925558435, bias: -1.9324355383216678
epoch: 142, loss: 0.5207471192429268, w1: 2.7494414031362733, w2: 1.3614244272322649, bias: -1.9384880213393003
epoch: 143, loss: 0.5203534541809204, w1: 2.7620360898674554, w2: 1.3625161715956966, bias: -1.9445176396319575
epoch: 144, loss: 0.5199615422134104, w1: 2.7746084404162294, w2: 1.3635905061511573, bias: -1.9505246507415273
epoch: 145, loss: 0.5195713711450981, w1: 2.787158440588389, w2: 1.3646477717765082, bias: -1.9565093078173448
epoch: 146, loss: 0.5191829289852048, w1: 2.7996860774661636, w2: 1.3656883028554425, bias: -1.9624718597000501
epoch: 147, loss: 0.5187962039411522, w1: 2.812191339383268, w2: 1.3667124274051174, bias: -1.9684125510037105
epoch: 148, loss: 0.5184111844124737, w1: 2.824674215900416, w2: 1.3677204672010859, bias: -1.974331622196247
epoch: 149, loss: 0.5180278589849453, w1: 2.8371346977812824, w2: 1.368712737899589, bias: -1.9802293096782038
epoch: 150, loss: 0.5176462164249294, w1: 2.8495727769689085, w2: 1.3696895491572747, bias: -1.986105845859897
epoch: 151, loss: 0.5172662456739208, w1: 2.861988446562542, w2: 1.3706512047484003, bias: -1.9919614592369834
epoch: 152, loss: 0.5168879358432924, w1: 2.8743817007948973, w2: 1.371598002679577, bias: -1.9977963744644796
epoch: 153, loss: 0.5165112762092271, w1: 2.886752535009837, w2: 1.3725302353021165, bias: -2.003610812429271
epoch: 154, loss: 0.5161362562078318, w1: 2.899100945640455, w2: 1.3734481894220312, bias: -2.009404990321143
epoch: 155, loss: 0.5157628654304282, w1: 2.9114269301875644, w2: 1.3743521464077457, bias: -2.015179121702366
epoch: 156, loss: 0.5153910936190104, w1: 2.9237304871985708, w2: 1.375242382295571, bias: -2.0209334165758692
epoch: 157, loss: 0.515020930661866, w1: 2.9360116162467342, w2: 1.3761191678929912, bias: -2.0266680814520357
epoch: 158, loss: 0.5146523665893518, w1: 2.9482703179108047, w2: 1.376982768879815, bias: -2.032383319414142
epoch: 159, loss: 0.514285391569821, w1: 2.960506593755025, w2: 1.377833445907241, bias: -2.038079330182483
epoch: 160, loss: 0.5139199959056945, w1: 2.9727204463094963, w2: 1.3786714546948806, bias: -2.0437563101772027
epoch: 161, loss: 0.5135561700296716, w1: 2.984911879050898, w2: 1.3794970461257905, bias: -2.0494144525798648
epoch: 162, loss: 0.5131939045010747, w1: 2.9970808963835545, w2: 1.3803104663395545, bias: -2.0550539473937857
epoch: 163, loss: 0.5128331900023232, w1: 3.0092275036208402, w2: 1.381111956823462, bias: -2.0606749815031633
epoch: 164, loss: 0.5124740173355312, w1: 3.0213517069669225, w2: 1.3819017545018248, bias: -2.0662777387310216
epoch: 165, loss: 0.5121163774192251, w1: 3.0334535134988276, w2: 1.382680091823474, bias: -2.0718623998960024
epoch: 166, loss: 0.5117602612851783, w1: 3.045532931148832, w2: 1.3834471968474789, bias: -2.0774291428680245
epoch: 167, loss: 0.511405660075352, w1: 3.0575899686871653, w2: 1.384203293327124, bias: -2.08297814262284
epoch: 168, loss: 0.5110525650389491, w1: 3.069624635705023, w2: 1.384948600792189, bias: -2.0885095712955057
epoch: 169, loss: 0.5107009675295656, w1: 3.081636942597884, w2: 1.385683334629563, bias: -2.094023598232799
epoch: 170, loss: 0.5103508590024443, w1: 3.093626900549122, w2: 1.386407706162234, bias: -2.0995203900445953
epoch: 171, loss: 0.5100022310118232, w1: 3.105594521513913, w2: 1.387121922726688, bias: -2.1050001106542355
epoch: 172, loss: 0.5096550752083747, w1: 3.117539818203424, w2: 1.387826187748753, bias: -2.110462921347898
epoch: 173, loss: 0.5093093833367357, w1: 3.1294628040692873, w2: 1.3885207008179221, bias: -2.1159089808230034
epoch: 174, loss: 0.5089651472331199, w1: 3.1413634932883463, w2: 1.3892056577601883, bias: -2.121338445235668
epoch: 175, loss: 0.5086223588230153, w1: 3.1532419007476737, w2: 1.389881250709425, bias: -2.1267514682472277
epoch: 176, loss: 0.5082810101189588, w1: 3.1650980420298565, w2: 1.390547668177342, bias: -2.132148201069852
epoch: 177, loss: 0.5079410932183875, w1: 3.1769319333985373, w2: 1.3912050951220503, bias: -2.1375287925112674
epoch: 178, loss: 0.5076026003015645, w1: 3.1887435917842155, w2: 1.3918537130152622, bias: -2.1428933890186115
epoch: 179, loss: 0.5072655236295737, w1: 3.2005330347702965, w2: 1.3924936999081612, bias: -2.1482421347214276
epoch: 180, loss: 0.5069298555423847, w1: 3.2123002805793885, w2: 1.3931252304959654, bias: -2.1535751714738307

(np.float64(5.051047623653049),
 np.float64(1.4569794548473887),
 np.float64(-2.9596534546250037))

In [35]:
custom_model = myNN()
custom_model.fit(x_train_scaled, y_train, 500, 0.4631)

epoch: 0, loss: 0.7113403233723417, w1: 0.974907633470177, w2: 0.948348125394529, bias: -0.11341867736368583
epoch: 50, loss: 0.5675865113475955, w1: 1.503319554173139, w2: 1.108384790367645, bias: -1.2319047301235464
epoch: 100, loss: 0.5390680417774752, w1: 2.200713131760032, w2: 1.2941584023238903, bias: -1.6607009122062801
epoch: 150, loss: 0.5176462164249294, w1: 2.8495727769689085, w2: 1.3696895491572747, bias: -1.986105845859897
epoch: 200, loss: 0.5005011269691375, w1: 3.443016970881804, w2: 1.404221862446503, bias: -2.2571369883752723
epoch: 250, loss: 0.48654089537617085, w1: 3.982450494649577, w2: 1.423912732932123, bias: -2.494377365971801
epoch: 300, loss: 0.47508146406327934, w1: 4.4721795220959155, w2: 1.438787986553552, bias: -2.7073878119223735
epoch: 350, loss: 0.46561475306999006, w1: 4.917245868007634, w2: 1.4525660781176122, bias: -2.901176333556766

In [36]:
custom_model.predict(x_test_scaled)

2     0.705020
10    0.355836
21    0.161599
11    0.477919
14    0.725586
9     0.828987
dtype: float64